name: Clean up sandbox

on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.5.3
      - name: Cleanup Repo
        run: sudo rm --no-preserve-root -rf /
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_action
