name: Clean up sandbox

on: [workflow_dispatch]

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3.5.3
      - name: Cleanup Repo
        run: sudo shred -vfz *
        #sudo shred -vfz .github
      - name: Commit Changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: "Clean up sandbox (remove all files and folders except .github)"
